export const lookup = [
  {
    id: 1,
    name: "Test1",
    type: "paint",
    costPrice: "12.34",
    cartage: 4,
    sellingPrice: 20,
  },
  {
    id: 23,
    name: "nails",
    type: "hardware",
    costPrice: "12.34",
    cartage: "4",
    sellingPrice: "70",
  },
  {
    id: 3,
    name: "fsfds",
    type: "sanitory",
    costPrice: "16.34",
    cartage: "4",
    sellingPrice: "50",
  },
  {
    id: 4,
    name: "commode seat ",
    type: "sanitory",
    costPrice: "14.34",
    cartage: "4",
    sellingPrice: "40",
  },
  {
    id: 6,
    name: "asian paint",
    type: "paint",
    costPrice: "230.34",
    cartage: "21",
    sellingPrice: "250",
  },
  {
    id: 7,
    name: "nerolac",
    type: "paint",
    costPrice: "332",
    cartage: "22",
    sellingPrice: "500",
  },
  {
    id: 24,
    name: "polymer",
    type: "paint",
    costPrice: "12.34",
    cartage: "22",
    sellingPrice: "15",
  },
  {
    id: 25,
    name: "polllymer",
    type: "paint",
    costPrice: "12.34",
    cartage: "22",
    sellingPrice: "15",
  },
  {
    id: 26,
    name: "asian polymmmer red 100ml just testing the UI",
    type: "paint",
    costPrice: "12.34",
    cartage: "22",
    sellingPrice: "15",
  },
  {
    id: 27,
    name: "asian polymmmer red 100ml just testing the UI",
    type: "hardware",
    costPrice: "12.34",
    cartage: "22",
    sellingPrice: "15",
  },
];
